<?php
/**
 * Bundled demonstration tenders.
 *
 * These stand in for the external tender API until its credentials are wired
 * up on the settings screen. Deadlines are stored as day-offsets from "today"
 * so the demo never goes stale while it is being shown around.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class TG_Sample_Data {

	public static function sectors() {
		return array(
			'Energy & Power',
			'Water & Sanitation',
			'Health & Medical Supplies',
			'Construction & Infrastructure',
			'ICT & Digital Services',
			'Agriculture & Food Security',
			'Transport & Logistics',
			'Education & Training',
			'Oil, Gas & Petrochemicals',
			'Mining & Minerals',
		);
	}

	public static function countries() {
		return array(
			'Kenya'        => 'KE',
			'Tanzania'     => 'TZ',
			'Ghana'        => 'GH',
			'Nigeria'      => 'NG',
			'Ethiopia'     => 'ET',
			'Uganda'       => 'UG',
			'Rwanda'       => 'RW',
			'Zambia'       => 'ZM',
			'Senegal'      => 'SN',
			'Egypt'        => 'EG',
			'Morocco'      => 'MA',
			'Mozambique'   => 'MZ',
			'Namibia'      => 'NA',
			'Côte d\'Ivoire' => 'CI',
			'Botswana'     => 'BW',
		);
	}

	/**
	 * @return array List of tender records in the gateway's normalised shape.
	 */
	public static function tenders() {
		$rows = self::rows();
		$out  = array();

		foreach ( $rows as $row ) {
			$published = gmdate( 'Y-m-d', strtotime( '-' . (int) $row['published_days_ago'] . ' days' ) );
			$deadline  = gmdate( 'Y-m-d', strtotime( '+' . (int) $row['deadline_in_days'] . ' days' ) );

			$out[] = array(
				'id'          => $row['id'],
				'reference'   => $row['reference'],
				'title'       => $row['title'],
				'buyer'       => $row['buyer'],
				'country'     => $row['country'],
				'sector'      => $row['sector'],
				'summary'     => $row['summary'],
				'description' => $row['description'],
				'value'       => $row['value'],
				'currency'    => $row['currency'],
				'published'   => $published,
				'deadline'    => $deadline,
				'method'      => $row['method'],
				'source_name' => $row['source'],
				'contact'     => $row['contact'],
				'documents'   => $row['documents'],
				'eligibility' => $row['eligibility'],
			);
		}

		return $out;
	}

	private static function rows() {
		return array(
			array(
				'id'                 => 'KE-MOEP-2026-0143',
				'reference'          => 'MOEP/ICB/2026/0143',
				'title'              => 'Supply and Installation of 40 MW Solar PV Plant with Battery Storage - Garissa County',
				'buyer'              => 'Ministry of Energy and Petroleum',
				'country'            => 'Kenya',
				'sector'             => 'Energy & Power',
				'summary'            => 'Turnkey design, supply, installation and 24-month operation of a 40 MW grid-connected solar plant with 15 MWh battery storage.',
				'description'        => "The Ministry of Energy and Petroleum invites sealed bids from eligible international suppliers for the design, supply, installation, testing and commissioning of a 40 MW grid-connected solar photovoltaic plant with 15 MWh of battery energy storage in Garissa County.\n\nThe scope covers PV modules, inverters, mounting structures, LV/MV switchgear, a 33/132 kV step-up substation, SCADA integration with the national grid operator, civil works, and a 24-month operation and maintenance period following provisional acceptance.\n\nBidders must demonstrate completion of at least two utility-scale solar projects of 20 MW or above within the last seven years.",
				'value'              => 48500000,
				'currency'           => 'USD',
				'published_days_ago' => 9,
				'deadline_in_days'   => 34,
				'method'             => 'International Competitive Bidding',
				'source'             => 'Public Procurement Regulatory Authority (Kenya)',
				'contact'            => array(
					'name'  => 'Head of Supply Chain Management',
					'org'   => 'Ministry of Energy and Petroleum, Nyayo House, Nairobi',
					'email' => 'procurement@energy.go.ke.example',
					'phone' => '+254 20 000 0000',
				),
				'documents'          => array(
					array( 'label' => 'Invitation to Bid (EN)', 'size' => '412 KB' ),
					array( 'label' => 'Technical Specifications - Volume II', 'size' => '3.1 MB' ),
					array( 'label' => 'Bill of Quantities (XLSX)', 'size' => '186 KB' ),
					array( 'label' => 'Draft Contract Conditions', 'size' => '740 KB' ),
				),
				'eligibility'        => array(
					'Bid security of USD 480,000 or equivalent, valid 150 days',
					'Average annual turnover of USD 60 million over the last 3 financial years',
					'Two comparable utility-scale solar EPC contracts completed since 2019',
					'Local content participation of not less than 20% of contract value',
				),
			),
			array(
				'id'                 => 'TZ-MOW-2026-0088',
				'reference'          => 'MoW/ICB/2025-26/0088',
				'title'              => 'Construction of Water Treatment Plant and 62 km Transmission Main - Dodoma',
				'buyer'              => 'Ministry of Water',
				'country'            => 'Tanzania',
				'sector'             => 'Water & Sanitation',
				'summary'            => 'Design-and-build of a 60,000 m3/day water treatment plant, intake works and 62 km of DN800 transmission pipeline.',
				'description'        => "The Ministry of Water invites bids for the design and construction of a 60,000 m3/day conventional water treatment plant serving the Dodoma capital district, together with river intake works, a raw water pumping station, 62 km of DN800 ductile iron transmission main, two 10,000 m3 reinforced concrete reservoirs and associated electromechanical works.\n\nThe contract is on a design-and-build basis under FIDIC Yellow Book conditions with a 12-month defects notification period. Financing is provided in part by a multilateral development partner and procurement follows the financier's international competitive bidding rules.",
				'value'              => 71200000,
				'currency'           => 'USD',
				'published_days_ago' => 14,
				'deadline_in_days'   => 41,
				'method'             => 'International Competitive Bidding',
				'source'             => 'Tanzania National e-Procurement System (NeST)',
				'contact'            => array(
					'name'  => 'Secretary, Ministerial Tender Board',
					'org'   => 'Ministry of Water, Government City, Mtumba, Dodoma',
					'email' => 'tenders@maji.go.tz.example',
					'phone' => '+255 26 000 0000',
				),
				'documents'          => array(
					array( 'label' => 'Bidding Document Volume I - Instructions', 'size' => '2.4 MB' ),
					array( 'label' => 'Employer\'s Requirements', 'size' => '5.8 MB' ),
					array( 'label' => 'Geotechnical Investigation Report', 'size' => '9.2 MB' ),
				),
				'eligibility'        => array(
					'Bid security of USD 700,000, valid 180 days',
					'Minimum average annual construction turnover of USD 85 million',
					'One water treatment plant of 40,000 m3/day or above delivered since 2018',
					'Joint ventures permitted; lead partner must meet 60% of each criterion',
				),
			),
			array(
				'id'                 => 'GH-MOH-2026-0311',
				'reference'          => 'MOH/GOODS/2026/0311',
				'title'              => 'Framework Supply of Haemodialysis Consumables and Reagents - 24 Months',
				'buyer'              => 'Ministry of Health / Central Medical Stores',
				'country'            => 'Ghana',
				'sector'             => 'Health & Medical Supplies',
				'summary'            => 'Two-year framework agreement for dialysers, bloodline sets, concentrates and reagents across 38 public dialysis centres.',
				'description'        => "The Ministry of Health, acting through the Central Medical Stores, invites bids for a 24-month framework agreement for the supply and delivery of haemodialysis consumables to 38 public dialysis centres nationwide.\n\nLots may be bid individually. Lot 1 covers dialysers and bloodline sets, Lot 2 covers acid and bicarbonate concentrates, Lot 3 covers water treatment consumables and reagents. Delivery is DDP to the Central Medical Stores in Tema with call-off quantities issued quarterly.\n\nAll products must carry current CE marking or US FDA clearance and be registered with the Ghana Food and Drugs Authority prior to first delivery.",
				'value'              => 9400000,
				'currency'           => 'USD',
				'published_days_ago' => 5,
				'deadline_in_days'   => 21,
				'method'             => 'International Competitive Tendering',
				'source'             => 'Public Procurement Authority (Ghana)',
				'contact'            => array(
					'name'  => 'Director of Procurement',
					'org'   => 'Ministry of Health, Ministries, Accra',
					'email' => 'procurement@moh.gov.gh.example',
					'phone' => '+233 30 000 0000',
				),
				'documents'          => array(
					array( 'label' => 'Tender Document (3 Lots)', 'size' => '1.7 MB' ),
					array( 'label' => 'Schedule of Requirements and Estimated Volumes', 'size' => '320 KB' ),
					array( 'label' => 'Framework Agreement Template', 'size' => '540 KB' ),
				),
				'eligibility'        => array(
					'Manufacturer authorisation letter for each item offered',
					'ISO 13485 certification of the manufacturing site',
					'Bid security of 2% of the lot value',
					'Evidence of two comparable public-sector supply contracts since 2021',
				),
			),
			array(
				'id'                 => 'NG-FMWH-2026-0027',
				'reference'          => 'FMWH/RD/ICB/2026/027',
				'title'              => 'Rehabilitation and Dualisation of 87 km Federal Highway Section - Kaduna to Zaria',
				'buyer'              => 'Federal Ministry of Works and Housing',
				'country'            => 'Nigeria',
				'sector'             => 'Construction & Infrastructure',
				'summary'            => 'Full-depth rehabilitation and dualisation of 87 km of federal highway including 4 interchanges and 11 bridges.',
				'description'        => "The Federal Ministry of Works and Housing invites prequalified and interested contractors to bid for the rehabilitation and dualisation of an 87 km section of federal highway between Kaduna and Zaria.\n\nWorks include full-depth pavement reconstruction, construction of a second carriageway, four grade-separated interchanges, eleven bridge structures, drainage, street lighting on urban sections and permanent road furniture. The contract period is 36 months with a 12-month defects liability period.",
				'value'              => 214000000,
				'currency'           => 'USD',
				'published_days_ago' => 18,
				'deadline_in_days'   => 27,
				'method'             => 'International Competitive Bidding',
				'source'             => 'Bureau of Public Procurement (Nigeria)',
				'contact'            => array(
					'name'  => 'Director, Procurement Department',
					'org'   => 'Federal Ministry of Works and Housing, Mabushi, Abuja',
					'email' => 'tenders@works.gov.ng.example',
					'phone' => '+234 9 000 0000',
				),
				'documents'          => array(
					array( 'label' => 'Invitation for Bids', 'size' => '288 KB' ),
					array( 'label' => 'Engineering Drawings (Part 1 of 3)', 'size' => '18.4 MB' ),
					array( 'label' => 'Bill of Quantities', 'size' => '1.1 MB' ),
					array( 'label' => 'Environmental and Social Management Plan', 'size' => '4.6 MB' ),
				),
				'eligibility'        => array(
					'Category A registration with the Bureau of Public Procurement',
					'Minimum average annual turnover of USD 180 million',
					'Two highway contracts of at least 50 km completed since 2017',
					'Bid security of USD 2.1 million',
				),
			),
			array(
				'id'                 => 'ET-EEU-2026-0402',
				'reference'          => 'EEU/ICB/G/2026/402',
				'title'              => 'Supply of 132 kV Power Transformers, Switchgear and Protection Panels',
				'buyer'              => 'Ethiopian Electric Utility',
				'country'            => 'Ethiopia',
				'sector'             => 'Energy & Power',
				'summary'            => 'Supply of 18 power transformers (132/33 kV), associated switchgear and numerical protection panels for grid reinforcement.',
				'description'        => "Ethiopian Electric Utility invites sealed bids for the supply, delivery and supervision of installation of eighteen 132/33 kV power transformers rated between 25 MVA and 63 MVA, together with 132 kV gas-insulated switchgear bays, numerical protection and control panels, and associated spares.\n\nDelivery is CIP Djibouti Port with onward inland transport arranged by the purchaser. The supply is split into three lots by substation cluster and bidders may bid for one or more lots.",
				'value'              => 33800000,
				'currency'           => 'USD',
				'published_days_ago' => 3,
				'deadline_in_days'   => 46,
				'method'             => 'International Competitive Bidding',
				'source'             => 'Ethiopian Public Procurement and Property Authority',
				'contact'            => array(
					'name'  => 'Procurement and Contract Administration',
					'org'   => 'Ethiopian Electric Utility, Addis Ababa',
					'email' => 'icb@eeu.gov.et.example',
					'phone' => '+251 11 000 0000',
				),
				'documents'          => array(
					array( 'label' => 'Bidding Document (3 Lots)', 'size' => '2.9 MB' ),
					array( 'label' => 'Technical Data Sheets', 'size' => '1.4 MB' ),
					array( 'label' => 'Type Test Requirements', 'size' => '620 KB' ),
				),
				'eligibility'        => array(
					'Manufacturer of transformers or authorised representative',
					'Type test certificates from an accredited independent laboratory',
					'Bid security of 2% of bid price per lot',
					'Supply of comparable equipment to at least three utilities since 2019',
				),
			),
			array(
				'id'                 => 'UG-MOICT-2026-0059',
				'reference'          => 'MoICT/SRVCS/2026/059',
				'title'              => 'Design and Implementation of National Digital Identity Verification Platform',
				'buyer'              => 'Ministry of ICT and National Guidance',
				'country'            => 'Uganda',
				'sector'             => 'ICT & Digital Services',
				'summary'            => 'End-to-end build of a national identity verification API platform serving banks, telcos and government agencies.',
				'description'        => "The Ministry of ICT and National Guidance seeks a qualified systems integrator to design, build, deploy and support a national digital identity verification platform.\n\nScope covers the verification API gateway, consent management, biometric matching integration with the existing national ID register, a partner onboarding portal, billing and settlement for verification transactions, and a 36-month support and maintenance period. The solution must be deployable in the National Data Centre with an active-passive disaster recovery site.",
				'value'              => 12600000,
				'currency'           => 'USD',
				'published_days_ago' => 7,
				'deadline_in_days'   => 30,
				'method'             => 'Quality and Cost Based Selection',
				'source'             => 'Public Procurement and Disposal of Public Assets Authority (Uganda)',
				'contact'            => array(
					'name'  => 'Head, Procurement and Disposal Unit',
					'org'   => 'Ministry of ICT and National Guidance, Kampala',
					'email' => 'pdu@ict.go.ug.example',
					'phone' => '+256 41 000 0000',
				),
				'documents'          => array(
					array( 'label' => 'Request for Proposals', 'size' => '1.9 MB' ),
					array( 'label' => 'Terms of Reference', 'size' => '860 KB' ),
					array( 'label' => 'Existing Systems Landscape', 'size' => '1.2 MB' ),
				),
				'eligibility'        => array(
					'Two national-scale identity or payments platforms delivered since 2018',
					'ISO 27001 certification',
					'Proposed team lead with 10+ years in national digital public infrastructure',
					'Technical proposal weighted 80%, financial 20%',
				),
			),
			array(
				'id'                 => 'RW-RAB-2026-0176',
				'reference'          => 'RAB/GOODS/2026/176',
				'title'              => 'Supply of Drip Irrigation Systems and Greenhouses for 1,200 Hectares',
				'buyer'              => 'Rwanda Agriculture and Animal Resources Development Board',
				'country'            => 'Rwanda',
				'sector'             => 'Agriculture & Food Security',
				'summary'            => 'Supply and installation of drip irrigation networks, pumping stations and 240 commercial greenhouses across four districts.',
				'description'        => "The Rwanda Agriculture and Animal Resources Development Board invites bids for the supply and installation of drip irrigation systems covering 1,200 hectares across four districts, including solar-powered pumping stations, filtration units, main and sub-main networks, fertigation equipment and 240 commercial greenhouses of 500 m2 each.\n\nThe contract includes farmer training, a two-year spare parts supply commitment and a one-year performance guarantee on all installed systems.",
				'value'              => 8900000,
				'currency'           => 'USD',
				'published_days_ago' => 11,
				'deadline_in_days'   => 19,
				'method'             => 'Open International Tender',
				'source'             => 'Rwanda Public Procurement Authority',
				'contact'            => array(
					'name'  => 'Director of Procurement Unit',
					'org'   => 'RAB Headquarters, Rubirizi, Kigali',
					'email' => 'procurement@rab.gov.rw.example',
					'phone' => '+250 78 000 0000',
				),
				'documents'          => array(
					array( 'label' => 'Tender Document', 'size' => '1.3 MB' ),
					array( 'label' => 'Site Schedule and Hectarage per District', 'size' => '210 KB' ),
				),
				'eligibility'        => array(
					'Bid security of RWF 90,000,000 or equivalent',
					'Two irrigation projects of 400 ha or above completed since 2020',
					'Local after-sales presence or committed partnership',
				),
			),
			array(
				'id'                 => 'ZM-MOH-2026-0233',
				'reference'          => 'MoH/HW/ICB/2026/233',
				'title'              => 'Construction and Equipping of Four District Hospitals - 120 Beds Each',
				'buyer'              => 'Ministry of Health',
				'country'            => 'Zambia',
				'sector'             => 'Health & Medical Supplies',
				'summary'            => 'Turnkey construction and medical equipping of four 120-bed district hospitals including theatres, imaging and staff housing.',
				'description'        => "The Ministry of Health invites bids for the turnkey design, construction, equipping and commissioning of four 120-bed district hospitals. Each facility comprises outpatient and inpatient blocks, two operating theatres, a maternity wing, laboratory, radiology department with CT and X-ray, a mortuary, central sterile services, staff housing, standby generation and a borehole water supply.\n\nThe medical equipment package is included in the scope and must be supplied with a three-year warranty and biomedical engineering training.",
				'value'              => 96500000,
				'currency'           => 'USD',
				'published_days_ago' => 22,
				'deadline_in_days'   => 15,
				'method'             => 'International Competitive Bidding',
				'source'             => 'Zambia Public Procurement Authority',
				'contact'            => array(
					'name'  => 'Chief Procurement Officer',
					'org'   => 'Ministry of Health, Ndeke House, Lusaka',
					'email' => 'tender@moh.gov.zm.example',
					'phone' => '+260 21 000 0000',
				),
				'documents'          => array(
					array( 'label' => 'Bidding Document', 'size' => '3.3 MB' ),
					array( 'label' => 'Architectural and Structural Drawings', 'size' => '22.7 MB' ),
					array( 'label' => 'Medical Equipment Schedule', 'size' => '780 KB' ),
				),
				'eligibility'        => array(
					'Bid security of USD 950,000',
					'Two hospital projects of 80 beds or above completed since 2018',
					'Nominated medical equipment partner with regional service capability',
				),
			),
			array(
				'id'                 => 'SN-SENELEC-2026-0064',
				'reference'          => 'SENELEC/AOI/2026/064',
				'title'              => 'Supply and Deployment of 350,000 Smart Prepaid Electricity Meters',
				'buyer'              => 'Société Nationale d\'Électricité (SENELEC)',
				'country'            => 'Senegal',
				'sector'             => 'Energy & Power',
				'summary'            => 'Supply, deployment and head-end integration of 350,000 STS-compliant smart prepaid meters over 30 months.',
				'description'        => "SENELEC invites international bids for the supply, installation and commissioning of 350,000 single-phase and three-phase STS-compliant smart prepaid electricity meters, together with a meter data management system, head-end system, vending integration and communications infrastructure.\n\nDeployment is phased over 30 months across the Dakar, Thiès and Saint-Louis regions. The bidder is responsible for integration with SENELEC's existing commercial system and for training of utility staff.",
				'value'              => 57300000,
				'currency'           => 'EUR',
				'published_days_ago' => 6,
				'deadline_in_days'   => 38,
				'method'             => 'Appel d\'Offres International',
				'source'             => 'Direction Centrale des Marchés Publics (Sénégal)',
				'contact'            => array(
					'name'  => 'Direction des Approvisionnements',
					'org'   => 'SENELEC, 28 Rue Vincens, Dakar',
					'email' => 'marches@senelec.sn.example',
					'phone' => '+221 33 000 0000',
				),
				'documents'          => array(
					array( 'label' => 'Dossier d\'Appel d\'Offres (FR)', 'size' => '2.6 MB' ),
					array( 'label' => 'Spécifications Techniques', 'size' => '1.8 MB' ),
					array( 'label' => 'Calendrier de Déploiement', 'size' => '340 KB' ),
				),
				'eligibility'        => array(
					'STS Association membership and current certification',
					'Deployment of at least 200,000 prepaid meters for one utility since 2019',
					'Bid security of EUR 570,000',
					'French-language documentation and support required',
				),
			),
			array(
				'id'                 => 'EG-NAT-2026-0091',
				'reference'          => 'NAT/ICB/2026/091',
				'title'              => 'Supply of 120 Standard-Gauge Passenger Coaches and Spare Parts Package',
				'buyer'              => 'National Authority for Tunnels',
				'country'            => 'Egypt',
				'sector'             => 'Transport & Logistics',
				'summary'            => 'Manufacture and delivery of 120 air-conditioned passenger coaches with a 10-year spare parts and maintenance support package.',
				'description'        => "The National Authority for Tunnels invites bids for the manufacture, supply, delivery and commissioning of 120 standard-gauge air-conditioned passenger coaches, together with a ten-year strategic spare parts package, special tools, depot equipment and technical training.\n\nBidders must propose a technology transfer and local assembly component of not less than 25% of contract value, to be executed with an Egyptian industrial partner.",
				'value'              => 388000000,
				'currency'           => 'USD',
				'published_days_ago' => 26,
				'deadline_in_days'   => 52,
				'method'             => 'International Competitive Bidding',
				'source'             => 'Egyptian Government Procurement Portal',
				'contact'            => array(
					'name'  => 'General Directorate of Contracts',
					'org'   => 'National Authority for Tunnels, Cairo',
					'email' => 'contracts@nat.gov.eg.example',
					'phone' => '+20 2 0000 0000',
				),
				'documents'          => array(
					array( 'label' => 'Invitation to Tender (EN/AR)', 'size' => '1.5 MB' ),
					array( 'label' => 'Rolling Stock Technical Specification', 'size' => '11.9 MB' ),
					array( 'label' => 'Local Content Requirements', 'size' => '460 KB' ),
				),
				'eligibility'        => array(
					'Rolling stock manufacturer with 500+ coaches delivered since 2015',
					'Bid bond of USD 3.9 million',
					'Committed Egyptian industrial partner for local assembly',
				),
			),
			array(
				'id'                 => 'MA-ONEE-2026-0138',
				'reference'          => 'ONEE/AOI/2026/138',
				'title'              => 'Design and Construction of Seawater Desalination Plant - 100,000 m3/day',
				'buyer'              => 'Office National de l\'Électricité et de l\'Eau Potable (ONEE)',
				'country'            => 'Morocco',
				'sector'             => 'Water & Sanitation',
				'summary'            => 'EPC of a 100,000 m3/day reverse osmosis desalination plant with intake, outfall and 18 km product water main.',
				'description'        => "ONEE invites international bids for the engineering, procurement and construction of a seawater reverse osmosis desalination plant with a capacity of 100,000 m3/day, expandable to 150,000 m3/day.\n\nThe scope includes marine intake and brine outfall structures, pre-treatment, two-pass reverse osmosis trains, energy recovery, remineralisation, a 20,000 m3 product water reservoir, an 18 km DN900 product water main and a dedicated 60 kV supply. A five-year operation and maintenance period follows commissioning.",
				'value'              => 189000000,
				'currency'           => 'EUR',
				'published_days_ago' => 16,
				'deadline_in_days'   => 44,
				'method'             => 'Appel d\'Offres International Restreint',
				'source'             => 'Portail des Marchés Publics (Maroc)',
				'contact'            => array(
					'name'  => 'Division des Achats',
					'org'   => 'ONEE - Branche Eau, Rabat',
					'email' => 'ao@onee.ma.example',
					'phone' => '+212 5 37 00 00 00',
				),
				'documents'          => array(
					array( 'label' => 'Avis d\'Appel d\'Offres', 'size' => '380 KB' ),
					array( 'label' => 'Cahier des Prescriptions Spéciales', 'size' => '6.4 MB' ),
					array( 'label' => 'Études Océanographiques', 'size' => '14.2 MB' ),
				),
				'eligibility'        => array(
					'Prequalification required before bid submission',
					'One SWRO plant of 60,000 m3/day or above commissioned since 2016',
					'Bid security of EUR 1.9 million',
				),
			),
			array(
				'id'                 => 'MZ-MIREME-2026-0052',
				'reference'          => 'MIREME/CI/2026/052',
				'title'              => 'Rural Electrification: Supply of Solar Home Systems and Mini-Grids for 210 Villages',
				'buyer'              => 'Ministry of Mineral Resources and Energy',
				'country'            => 'Mozambique',
				'sector'             => 'Energy & Power',
				'summary'            => 'Supply and installation of 46,000 solar home systems and 28 village mini-grids with 5-year O&M.',
				'description'        => "The Ministry of Mineral Resources and Energy invites bids for a rural electrification programme covering 210 villages in Nampula, Zambézia and Cabo Delgado provinces.\n\nLot 1 covers the supply and installation of 46,000 solar home systems with mobile-money enabled pay-as-you-go controllers. Lot 2 covers 28 village mini-grids totalling 4.2 MW with distribution networks and connections. Both lots include a five-year operation and maintenance obligation and local technician training.",
				'value'              => 41700000,
				'currency'           => 'USD',
				'published_days_ago' => 2,
				'deadline_in_days'   => 48,
				'method'             => 'International Competitive Bidding',
				'source'             => 'Portal de Contratação Pública (Moçambique)',
				'contact'            => array(
					'name'  => 'Unidade Gestora Executora das Aquisições',
					'org'   => 'MIREME, Av. Fernão de Magalhães, Maputo',
					'email' => 'ugea@mireme.gov.mz.example',
					'phone' => '+258 21 000 000',
				),
				'documents'          => array(
					array( 'label' => 'Documento de Concurso (PT/EN)', 'size' => '2.2 MB' ),
					array( 'label' => 'Village Schedule and Load Survey', 'size' => '1.6 MB' ),
				),
				'eligibility'        => array(
					'Lighting Global / VeraSol certification for all solar home systems',
					'Two mini-grid programmes of 1 MW or above delivered since 2019',
					'Portuguese-language field operations capability',
				),
			),
			array(
				'id'                 => 'NA-NAMPOWER-2026-0019',
				'reference'          => 'NPWR/ICB/2026/019',
				'title'              => 'Supply of Transmission Line Hardware and Conductors - 400 kV Corridor',
				'buyer'              => 'NamPower',
				'country'            => 'Namibia',
				'sector'             => 'Energy & Power',
				'summary'            => 'Supply of ACSR conductors, insulator strings, tower steel and line hardware for a 340 km 400 kV corridor.',
				'description'        => "NamPower invites bids for the supply and delivery of transmission line materials for a 340 km 400 kV transmission corridor, comprising ACSR conductors and OPGW, composite insulator strings, complete galvanised tower steel packages, line hardware, earthing materials and spares.\n\nDelivery is DDP to NamPower stores in Windhoek and Otjiwarongo on a phased schedule over 14 months.",
				'value'              => 62400000,
				'currency'           => 'USD',
				'published_days_ago' => 12,
				'deadline_in_days'   => 25,
				'method'             => 'International Competitive Bidding',
				'source'             => 'Central Procurement Board of Namibia',
				'contact'            => array(
					'name'  => 'Manager: Procurement',
					'org'   => 'NamPower Centre, 15 Luther Street, Windhoek',
					'email' => 'tenders@nampower.com.na.example',
					'phone' => '+264 61 000 000',
				),
				'documents'          => array(
					array( 'label' => 'Bidding Document', 'size' => '1.8 MB' ),
					array( 'label' => 'Material Schedules and Drawings', 'size' => '7.3 MB' ),
				),
				'eligibility'        => array(
					'Manufacturer or authorised distributor for each material category',
					'Bid security of NAD 12,000,000 or equivalent',
					'Type test certificates for conductors and insulators',
				),
			),
			array(
				'id'                 => 'CI-MPD-2026-0203',
				'reference'          => 'MPD/AOI/2026/203',
				'title'              => 'Construction of 60 Primary Schools and Supply of Furniture - Six Regions',
				'buyer'              => 'Ministère du Plan et du Développement',
				'country'            => 'Côte d\'Ivoire',
				'sector'             => 'Education & Training',
				'summary'            => 'Construction of 60 six-classroom primary schools with latrines, boreholes and full furniture supply.',
				'description'        => "The Ministère du Plan et du Développement invites bids for the construction of 60 primary schools across six regions. Each school comprises six classrooms, an administration block, separate latrine blocks, a borehole with hand pump, boundary fencing and a full package of pupil and teacher furniture.\n\nThe works are divided into six geographic lots. A bidder may be awarded a maximum of three lots. The contract period is 18 months per lot.",
				'value'              => 27300000,
				'currency'           => 'EUR',
				'published_days_ago' => 20,
				'deadline_in_days'   => 17,
				'method'             => 'Appel d\'Offres International',
				'source'             => 'Direction des Marchés Publics (Côte d\'Ivoire)',
				'contact'            => array(
					'name'  => 'Cellule de Passation des Marchés',
					'org'   => 'Ministère du Plan et du Développement, Abidjan-Plateau',
					'email' => 'marches@plan.gouv.ci.example',
					'phone' => '+225 27 20 00 00 00',
				),
				'documents'          => array(
					array( 'label' => 'Dossier d\'Appel d\'Offres (6 lots)', 'size' => '3.7 MB' ),
					array( 'label' => 'Plans Types et Devis Quantitatifs', 'size' => '8.9 MB' ),
				),
				'eligibility'        => array(
					'Bid security of EUR 90,000 per lot',
					'Three comparable building contracts completed since 2020',
					'Nominated site agent per lot with 8 years experience',
				),
			),
			array(
				'id'                 => 'BW-BPC-2026-0074',
				'reference'          => 'BPC/ICB/2026/074',
				'title'              => 'Supply of Coal Handling Plant Spares and Overhaul Services - Morupule',
				'buyer'              => 'Botswana Power Corporation',
				'country'            => 'Botswana',
				'sector'             => 'Mining & Minerals',
				'summary'            => 'Supply of conveyor, crusher and stacker-reclaimer spares plus a scheduled 90-day overhaul of the coal handling plant.',
				'description'        => "Botswana Power Corporation invites bids for the supply of coal handling plant spare parts and the execution of a scheduled overhaul at the Morupule power station.\n\nScope covers conveyor idlers, pulleys and belting, crusher wear parts, stacker-reclaimer components, dust suppression system refurbishment, and the labour, tooling and supervision for a 90-day outage window. Bidders must demonstrate the ability to mobilise a full overhaul crew to site.",
				'value'              => 15800000,
				'currency'           => 'USD',
				'published_days_ago' => 8,
				'deadline_in_days'   => 23,
				'method'             => 'International Competitive Bidding',
				'source'             => 'Public Procurement Regulatory Authority (Botswana)',
				'contact'            => array(
					'name'  => 'Procurement Manager - Generation',
					'org'   => 'Botswana Power Corporation, Gaborone',
					'email' => 'tenders@bpc.bw.example',
					'phone' => '+267 360 0000',
				),
				'documents'          => array(
					array( 'label' => 'Bidding Document', 'size' => '1.4 MB' ),
					array( 'label' => 'Spares Schedule and Drawings', 'size' => '5.1 MB' ),
					array( 'label' => 'Outage Programme', 'size' => '290 KB' ),
				),
				'eligibility'        => array(
					'OEM or OEM-authorised supplier for crusher and stacker components',
					'Two coal handling plant overhauls executed since 2019',
					'Bid security of BWP 2,000,000',
				),
			),
			array(
				'id'                 => 'KE-KEBS-2026-0421',
				'reference'          => 'KEBS/ICT/2026/0421',
				'title'              => 'Supply, Installation and Support of Laboratory Information Management System',
				'buyer'              => 'Kenya Bureau of Standards',
				'country'            => 'Kenya',
				'sector'             => 'ICT & Digital Services',
				'summary'            => 'Enterprise LIMS covering 14 laboratories with instrument integration, sample tracking and certification workflow.',
				'description'        => "The Kenya Bureau of Standards invites bids for the supply, configuration, data migration, deployment and three-year support of an enterprise Laboratory Information Management System covering fourteen accredited laboratories.\n\nThe system must support sample registration and chain of custody, instrument data capture, test scheduling, ISO/IEC 17025 compliance reporting, certificate generation and a customer self-service portal. Integration with the existing ERP and the national single window system is required.",
				'value'              => 4200000,
				'currency'           => 'USD',
				'published_days_ago' => 4,
				'deadline_in_days'   => 20,
				'method'             => 'International Competitive Tendering',
				'source'             => 'Public Procurement Regulatory Authority (Kenya)',
				'contact'            => array(
					'name'  => 'Head of Procurement',
					'org'   => 'Kenya Bureau of Standards, Popo Road, Nairobi',
					'email' => 'procurement@kebs.org.example',
					'phone' => '+254 20 000 0001',
				),
				'documents'          => array(
					array( 'label' => 'Tender Document', 'size' => '1.1 MB' ),
					array( 'label' => 'Functional Requirements Matrix', 'size' => '480 KB' ),
				),
				'eligibility'        => array(
					'Three LIMS deployments in accredited laboratories since 2019',
					'ISO/IEC 17025 domain expertise in the proposed team',
					'Tender security of KES 4,000,000',
				),
			),
			array(
				'id'                 => 'TZ-TANESCO-2026-0117',
				'reference'          => 'TANESCO/ICB/2026/117',
				'title'              => 'Supply of Distribution Transformers, Poles and Line Materials - Framework',
				'buyer'              => 'Tanzania Electric Supply Company (TANESCO)',
				'country'            => 'Tanzania',
				'sector'             => 'Energy & Power',
				'summary'            => 'Three-year framework for distribution transformers (50-315 kVA), concrete poles, ABC cable and accessories.',
				'description'        => "TANESCO invites bids for a three-year framework agreement for the supply and delivery of distribution transformers rated 50 kVA to 315 kVA, prestressed concrete poles, aerial bundled conductor, LV switchgear, meters and associated line accessories.\n\nOrders will be issued as call-offs against agreed unit rates. Bidders may bid for individual lots. Delivery is DDP to eight regional stores.",
				'value'              => 68900000,
				'currency'           => 'USD',
				'published_days_ago' => 13,
				'deadline_in_days'   => 29,
				'method'             => 'International Competitive Bidding',
				'source'             => 'Tanzania National e-Procurement System (NeST)',
				'contact'            => array(
					'name'  => 'Director of Procurement Management',
					'org'   => 'TANESCO, Ubungo, Dar es Salaam',
					'email' => 'tenders@tanesco.co.tz.example',
					'phone' => '+255 22 000 0000',
				),
				'documents'          => array(
					array( 'label' => 'Framework Bidding Document', 'size' => '2.1 MB' ),
					array( 'label' => 'Unit Rate Schedules', 'size' => '390 KB' ),
					array( 'label' => 'Technical Specifications', 'size' => '2.8 MB' ),
				),
				'eligibility'        => array(
					'Transformer manufacturer with routine and type test facilities',
					'Bid security of 2% per lot',
					'Two utility framework contracts executed since 2020',
				),
			),
			array(
				'id'                 => 'GH-GHAPOHA-2026-0087',
				'reference'          => 'GPHA/ICB/2026/087',
				'title'              => 'Supply of Two Mobile Harbour Cranes and Terminal Handling Equipment',
				'buyer'              => 'Ghana Ports and Harbours Authority',
				'country'            => 'Ghana',
				'sector'             => 'Transport & Logistics',
				'summary'            => 'Supply and commissioning of two 125-tonne mobile harbour cranes, 6 reach stackers and 12 terminal tractors.',
				'description'        => "The Ghana Ports and Harbours Authority invites bids for the supply, delivery, commissioning and operator training for two mobile harbour cranes with a minimum capacity of 125 tonnes at 18 m radius, six reach stackers, twelve terminal tractors and forty roll trailers for the Takoradi container terminal.\n\nA five-year full-service maintenance agreement including parts is required as part of the offer, together with a local spare parts holding at the port.",
				'value'              => 39600000,
				'currency'           => 'EUR',
				'published_days_ago' => 10,
				'deadline_in_days'   => 33,
				'method'             => 'International Competitive Tendering',
				'source'             => 'Public Procurement Authority (Ghana)',
				'contact'            => array(
					'name'  => 'Director, Procurement and Supply',
					'org'   => 'Ghana Ports and Harbours Authority, Tema',
					'email' => 'procurement@ghanaports.gov.gh.example',
					'phone' => '+233 30 000 0001',
				),
				'documents'          => array(
					array( 'label' => 'Tender Document', 'size' => '1.6 MB' ),
					array( 'label' => 'Equipment Technical Specifications', 'size' => '3.4 MB' ),
					array( 'label' => 'Maintenance Agreement Template', 'size' => '520 KB' ),
				),
				'eligibility'        => array(
					'OEM or OEM-appointed distributor',
					'Twenty mobile harbour cranes supplied worldwide since 2016',
					'Bid security of EUR 400,000',
					'Regional service centre within 8 hours travel of Tema',
				),
			),
			array(
				'id'                 => 'ET-EPSA-2026-0298',
				'reference'          => 'EPSA/ICB/2026/298',
				'title'              => 'Framework Supply of Essential Medicines - 42 Product Lines',
				'buyer'              => 'Ethiopian Pharmaceuticals Supply Agency',
				'country'            => 'Ethiopia',
				'sector'             => 'Health & Medical Supplies',
				'summary'            => 'Two-year framework for 42 essential medicine lines delivered CIP Djibouti with WHO prequalification required.',
				'description'        => "The Ethiopian Pharmaceuticals Supply Agency invites bids for a two-year framework agreement covering 42 essential medicine product lines including antibiotics, antimalarials, antiretrovirals, analgesics and paediatric formulations.\n\nAll products must be WHO prequalified or approved by a stringent regulatory authority, registered with the Ethiopian Food and Drug Authority, and delivered with a minimum of 80% of shelf life remaining at the point of arrival.",
				'value'              => 54100000,
				'currency'           => 'USD',
				'published_days_ago' => 1,
				'deadline_in_days'   => 40,
				'method'             => 'International Competitive Bidding',
				'source'             => 'Ethiopian Public Procurement and Property Authority',
				'contact'            => array(
					'name'  => 'Procurement Directorate',
					'org'   => 'Ethiopian Pharmaceuticals Supply Agency, Addis Ababa',
					'email' => 'tender@epsa.gov.et.example',
					'phone' => '+251 11 000 0001',
				),
				'documents'          => array(
					array( 'label' => 'Bidding Document and Price Schedules', 'size' => '2.7 MB' ),
					array( 'label' => 'Product Specifications (42 lines)', 'size' => '1.9 MB' ),
				),
				'eligibility'        => array(
					'WHO prequalification or SRA approval per product',
					'GMP certificate of the manufacturing site issued within 3 years',
					'Bid security of 1.5% of bid value',
				),
			),
			array(
				'id'                 => 'NG-NNPC-2026-0164',
				'reference'          => 'NNPC/UP/ICB/2026/164',
				'title'              => 'Provision of Integrated Well Services and Drilling Support - 3 Year Contract',
				'buyer'              => 'NNPC Upstream Investment Management Services',
				'country'            => 'Nigeria',
				'sector'             => 'Oil, Gas & Petrochemicals',
				'summary'            => 'Three-year integrated well services contract covering cementing, wireline, drilling fluids and completion services.',
				'description'        => "NNPC Upstream Investment Management Services invites technically and commercially qualified suppliers to bid for a three-year integrated well services contract covering onshore and swamp locations.\n\nScope includes drilling fluids and solids control, cementing services, wireline logging and perforation, fishing and remedial services, completion equipment supply and installation, and dedicated project management. Bidders must be registered on the industry joint qualification system and comply fully with the Nigerian Oil and Gas Industry Content Development Act.",
				'value'              => 143000000,
				'currency'           => 'USD',
				'published_days_ago' => 24,
				'deadline_in_days'   => 12,
				'method'             => 'International Competitive Bidding',
				'source'             => 'Nigerian Petroleum Exchange / NipeX',
				'contact'            => array(
					'name'  => 'Supply Chain Management Division',
					'org'   => 'NNPC Towers, Herbert Macaulay Way, Abuja',
					'email' => 'nipex.tenders@nnpc.gov.ng.example',
					'phone' => '+234 9 000 0001',
				),
				'documents'          => array(
					array( 'label' => 'Invitation to Technical Tender', 'size' => '640 KB' ),
					array( 'label' => 'Scope of Work', 'size' => '2.3 MB' ),
					array( 'label' => 'Nigerian Content Plan Template', 'size' => '410 KB' ),
				),
				'eligibility'        => array(
					'Current NipeX joint qualification system registration',
					'Nigerian Content Equipment Certificate',
					'Two integrated well services contracts executed since 2018',
					'HSE case and IOGP-compliant safety statistics',
				),
			),
			array(
				'id'                 => 'RW-WASAC-2026-0045',
				'reference'          => 'WASAC/ICB/2026/045',
				'title'              => 'Non-Revenue Water Reduction Programme - Kigali District Metered Areas',
				'buyer'              => 'Water and Sanitation Corporation (WASAC)',
				'country'            => 'Rwanda',
				'sector'             => 'Water & Sanitation',
				'summary'            => 'Performance-based contract to reduce non-revenue water from 38% to 22% across 46 district metered areas.',
				'description'        => "WASAC invites bids for a performance-based non-revenue water reduction contract covering 46 district metered areas in Kigali.\n\nThe contractor is responsible for DMA establishment and rehabilitation, pressure management, active leakage detection and repair, meter replacement of 62,000 customer connections, and the deployment of a network monitoring platform. Payment is partly fixed and partly linked to verified reductions in non-revenue water against a baseline of 38%.",
				'value'              => 23400000,
				'currency'           => 'USD',
				'published_days_ago' => 15,
				'deadline_in_days'   => 26,
				'method'             => 'Open International Tender',
				'source'             => 'Rwanda Public Procurement Authority',
				'contact'            => array(
					'name'  => 'Head of Procurement',
					'org'   => 'WASAC Ltd, Kacyiru, Kigali',
					'email' => 'procurement@wasac.rw.example',
					'phone' => '+250 78 000 0001',
				),
				'documents'          => array(
					array( 'label' => 'Bidding Document', 'size' => '2.0 MB' ),
					array( 'label' => 'Network Baseline Data and DMA Maps', 'size' => '12.6 MB' ),
				),
				'eligibility'        => array(
					'One performance-based NRW contract of 40,000 connections or above since 2019',
					'Bid security of USD 230,000',
					'Proposed NRW specialist with 12 years experience',
				),
			),
			array(
				'id'                 => 'UG-UNRA-2026-0112',
				'reference'          => 'UNRA/WRKS/2026/112',
				'title'              => 'Upgrading of 104 km District Road to Bituminous Standard - Northern Region',
				'buyer'              => 'Uganda National Roads Authority',
				'country'            => 'Uganda',
				'sector'             => 'Construction & Infrastructure',
				'summary'            => 'Upgrading 104 km of gravel road to bituminous standard including 3 bridges and 42 box culverts.',
				'description'        => "The Uganda National Roads Authority invites bids for the upgrading of 104 km of district road from gravel to bituminous standard in the Northern Region, including earthworks, sub-base and base course, double surface dressing, three reinforced concrete bridges, 42 box culverts, drainage and road safety furniture.\n\nThe contract period is 30 months with a 12-month defects liability period. The works include a compulsory community employment and HIV/AIDS awareness component.",
				'value'              => 88200000,
				'currency'           => 'USD',
				'published_days_ago' => 19,
				'deadline_in_days'   => 36,
				'method'             => 'International Competitive Bidding',
				'source'             => 'Public Procurement and Disposal of Public Assets Authority (Uganda)',
				'contact'            => array(
					'name'  => 'Head of Procurement and Disposal Unit',
					'org'   => 'UNRA, Plot 5 Lourdel Road, Kampala',
					'email' => 'procurement@unra.go.ug.example',
					'phone' => '+256 41 000 0001',
				),
				'documents'          => array(
					array( 'label' => 'Bidding Document', 'size' => '2.5 MB' ),
					array( 'label' => 'Design Report and Drawings', 'size' => '26.1 MB' ),
					array( 'label' => 'Bill of Quantities', 'size' => '900 KB' ),
				),
				'eligibility'        => array(
					'Bid security of USD 880,000',
					'Two road upgrading contracts of 60 km or above completed since 2018',
					'Minimum average annual turnover of USD 70 million',
				),
			),
			array(
				'id'                 => 'ZM-ZESCO-2026-0155',
				'reference'          => 'ZESCO/ICB/2026/155',
				'title'              => 'Refurbishment of Hydropower Station Units 1-4 and Governor Replacement',
				'buyer'              => 'ZESCO Limited',
				'country'            => 'Zambia',
				'sector'             => 'Energy & Power',
				'summary'            => 'Refurbishment of four 30 MW hydro units including turbine runners, generator rewind and digital governor replacement.',
				'description'        => "ZESCO Limited invites bids for the refurbishment of four 30 MW hydropower generating units, comprising turbine runner replacement, guide vane and wicket gate overhaul, generator stator rewind, excitation system replacement, digital governor supply and installation, and upgrade of the unit control and protection systems.\n\nWorks are to be executed one unit at a time to maintain station availability. The contract period is 42 months including a 24-month warranty on all refurbished equipment.",
				'value'              => 78500000,
				'currency'           => 'USD',
				'published_days_ago' => 17,
				'deadline_in_days'   => 31,
				'method'             => 'International Competitive Bidding',
				'source'             => 'Zambia Public Procurement Authority',
				'contact'            => array(
					'name'  => 'Director - Procurement and Supply Chain',
					'org'   => 'ZESCO Limited, Stand 6949 Great East Road, Lusaka',
					'email' => 'tenders@zesco.co.zm.example',
					'phone' => '+260 21 000 0001',
				),
				'documents'          => array(
					array( 'label' => 'Bidding Document', 'size' => '2.8 MB' ),
					array( 'label' => 'Condition Assessment Report', 'size' => '7.8 MB' ),
					array( 'label' => 'Outage Constraints and Programme', 'size' => '350 KB' ),
				),
				'eligibility'        => array(
					'OEM or specialist hydro refurbishment contractor',
					'Three hydro unit refurbishments of 20 MW or above since 2016',
					'Bid security of USD 780,000',
				),
			),
			array(
				'id'                 => 'EG-MOETE-2026-0208',
				'reference'          => 'MOETE/ICB/2026/208',
				'title'              => 'Supply of 260,000 Student Laptops and Digital Learning Platform Licences',
				'buyer'              => 'Ministry of Education and Technical Education',
				'country'            => 'Egypt',
				'sector'             => 'Education & Training',
				'summary'            => 'Supply of 260,000 ruggedised student laptops with 3-year warranty plus digital learning platform licensing and rollout.',
				'description'        => "The Ministry of Education and Technical Education invites bids for the supply, imaging, delivery and deployment support of 260,000 ruggedised student laptops for secondary schools, together with device management licensing, a digital learning platform for 3 years and nationwide teacher training.\n\nDevices must include a three-year on-site warranty with a nationwide service network, and the supplier must maintain a spare pool of 3% of units at regional service centres.",
				'value'              => 118000000,
				'currency'           => 'USD',
				'published_days_ago' => 21,
				'deadline_in_days'   => 18,
				'method'             => 'International Competitive Bidding',
				'source'             => 'Egyptian Government Procurement Portal',
				'contact'            => array(
					'name'  => 'General Administration for Tenders',
					'org'   => 'Ministry of Education, Cairo',
					'email' => 'tenders@moe.gov.eg.example',
					'phone' => '+20 2 0000 0001',
				),
				'documents'          => array(
					array( 'label' => 'Tender Document (EN/AR)', 'size' => '1.8 MB' ),
					array( 'label' => 'Device Technical Specification', 'size' => '760 KB' ),
					array( 'label' => 'Rollout and Training Plan Template', 'size' => '430 KB' ),
				),
				'eligibility'        => array(
					'OEM authorisation and MIL-STD-810 test evidence',
					'One supply of 100,000 devices or more to a public body since 2019',
					'Bid bond of USD 1.2 million',
					'Nationwide authorised service network in Egypt',
				),
			),
		);
	}
}
